language: python
python:
- "3.6"
cache: pip
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r requirements.txt -U --upgrade-strategy eager
- pip install -r test_requirements.txt
script:
- flake8 .
- travis_wait 50 py.test
after_success:
- coveralls
